### ISSUE TITLE
Wrong king attack range

### ISSUE THREAD

**Issue by Mohre** [SharifAIChallenge/AIC20-Game#1]
King attack range doest match document.
In the document King attack range is 5 but in all of the sample maps it is 4.
Which one is correct?
Please make them compatible.

**Comment by Mohre** [comment]
There are more inconsistency in the sample maps.
I listed them:

- "turnsToSpell": 4, should be 10

- king's "range": 4, should be 5

- DUPLICATE spell's "power": 2, should be 4

**Comment by mahdijavanmardigh** [comment]
They're fixed in new Maps

**Comment by Mohre** [comment]
Where are the new Maps?
