### ISSUE TITLE
Easy to use Visualizer

### ISSUE THREAD

**Issue by 733amir** [SharifAIChallenge/AIC20-Game#7]
I think it would be better if the **visualizer**'s `CSS` and `JS` code are moved to `HTML` file so opening `HTML` file with the browser would be enough and wouldn't require a static file server for **visualizer** to work correctly.

**Comment by 733amir** [comment]
I have created a pull request for this: #8

**Comment by Hamedamz** [comment]
Thanks. but there is no need to run a static file server!
